name: basel_alm
version: '0.1.0'
config-version: 2
profile: basel_alm

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  basel_alm:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
